# Generated by Django 3.0.6 on 2020-06-06 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.TextField(max_length=128)),
                ('name', models.TextField(max_length=128)),
                ('artist_id', models.TextField(max_length=128)),
                ('artist_name', models.TextField(max_length=128)),
                ('album_id', models.TextField(max_length=128)),
                ('album_name', models.TextField(max_length=128)),
                ('popularity', models.IntegerField()),
                ('url', models.URLField()),
                ('preview_url', models.URLField()),
                ('release_date', models.DateField()),
                ('played_at', models.DateTimeField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
